<a href="https://colab.research.google.com/github/ngohuy1811/AIO-Module/blob/main/bai_tap_week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
# Cau 1:
import torch
import torch.nn as nn

class Softmax(nn.Module):
  def __init__(self):
    super().__init__()

  def forward(self, x):
    exp_x = torch.exp(x)
    sum_exp_x = torch.sum(exp_x)
    softmax_output = exp_x / sum_exp_x
    return softmax_output

data = torch.Tensor([1, 2, 3])
softmax = Softmax()
output = softmax(data)

print("Softmax Output:", output)

Softmax Output: tensor([0.0900, 0.2447, 0.6652])


In [26]:
class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x)
        exp_x = torch.exp(x - x_max)
        sum_exp_x = torch.sum(exp_x)
        softmax_output = exp_x / sum_exp_x
        return softmax_output

softmax_stable = SoftmaxStable()
output_stable = softmax_stable(data)

print("Stable Softmax Output:", output_stable)

Stable Softmax Output: tensor([0.0900, 0.2447, 0.6652])


In [ ]:
# Cau 2a:
class Student:
  def __init__(self, name, yob, grade):
    self.name = name
    self.yob = yob
    self.grade = grade
  def describe(self):
    print(f'Student - Name: {self.name} - YoB: {self.yob} - Grade: {self.grade}')

class Doctor:
  def __init__(self, name, yob,specialist):
    self.name = name
    self.yob = yob
    self.specialist = specialist
  def describe(self):
    print(f'Doctor - Name: {self.name} - YoB: {self.yob} - Specialist: {self.specialist}')

class Teacher:
  def __init__(self, name, yob, subject):
    self.name = name
    self.yob = yob
    self.subject = subject
  def describe(self):
    print(f'Teacher - Name: {self.name} - YoB: {self.yob} - Subject: {self.subject}')

#Test case
student1 = Student ( name =" studentA ", yob =2010 , grade ="7")
student1.describe()

teacher1 = Teacher ( name =" teacherA ", yob =1969 , subject =" Math ")
teacher1.describe()

doctor1 = Doctor ( name = 'doctorA', yob =1945 , specialist =" Endocrinologists ")
doctor1.describe()

Student - Name:  studentA  - YoB: 2010 - Grade: 7
Teacher - Name:  teacherA  - YoB: 1969 - Subject:  Math 
Doctor - Name: doctorA - YoB: 1945 - Specialist:  Endocrinologists 


In [ ]:
# Cau 2 b,c
class Ward:
  def __init__(self, name):
    self.name = name
    self.ward_list = []

  def add_person(self, person):
      self.ward_list.append(person)

  def describe(self):
      print(f'Ward - Name: {self.name}')
      for person in self.ward_list:
          person.describe()

  def count_doctor(self):
        count = sum(isinstance(person, Doctor) for person in self.ward_list)
        return count

  def sort_age(self):
        self.ward_list.sort(key=lambda x: x.yob, reverse=True)

  def compute_average(self):
        teacher_yobs = [person.yob for person in self.ward_list if isinstance(person, Teacher)]
        if teacher_yobs:
            average_yob = sum(teacher_yobs) / len(teacher_yobs)
            return average_yob
        else:
            return None


#test case
teacher2 = Teacher ( name =" teacherB ", yob =1995 , subject =" History ")
doctor2 = Doctor ( name =" doctorB ", yob =1975 , specialist =" Cardiologists ")
ward1 = Ward( name =" Ward1 ")
ward1.add_person ( student1 )
ward1.add_person ( teacher1 )
ward1.add_person ( teacher2 )
ward1.add_person ( doctor1 )
ward1.add_person ( doctor2 )
ward1.describe ()
print ( f"Number of doctors : {ward1.count_doctor()}")





Ward - Name:  Ward1 
Student - Name:  studentA  - YoB: 2010 - Grade: 7
Teacher - Name:  teacherA  - YoB: 1969 - Subject:  Math 
Teacher - Name:  teacherB  - YoB: 1995 - Subject:  History 
Doctor - Name: doctorA - YoB: 1945 - Specialist:  Endocrinologists 
Doctor - Name:  doctorB  - YoB: 1975 - Specialist:  Cardiologists 
Number of doctors : 2


In [ ]:
#Cau 2 d
print ("After sorting Age of Ward1 people ")
ward1.sort_age ()
ward1.describe ()

After sorting Age of Ward1 people 
Ward - Name:  Ward1 
Student - Name:  studentA  - YoB: 2010 - Grade: 7
Teacher - Name:  teacherB  - YoB: 1995 - Subject:  History 
Doctor - Name:  doctorB  - YoB: 1975 - Specialist:  Cardiologists 
Teacher - Name:  teacherA  - YoB: 1969 - Subject:  Math 
Doctor - Name: doctorA - YoB: 1945 - Specialist:  Endocrinologists 


In [ ]:
#Cau 2 e
print (f"Average year of birth ( teachers ): {ward1.compute_average ()}")

Average year of birth ( teachers ): 1982.0


In [ ]:
#Cau 3

class MyStack:
  def __init__(self, capacity):
    self.data = []
    self.capacity = capacity

  def push(self,value):
      self.data.append(value)

  def pop(self):
    return self.data.pop(0)

  def is_empty(self):
    return len(self.data) == 0

  def is_full(self):
    return len(self.data) == self.capacity

  def top(self):
    return self.data[0]

#Test
stack1 = MyStack ( capacity =5)
stack1 . push (1)
stack1 . push (2)

print (stack1.is_full () )
print (stack1.top () )
print (stack1.pop () )
print ( stack1 . top () )
print ( stack1 . pop () )
print ( stack1 . is_empty () )

False
1
1
2
2
True


In [ ]:
#Cau 4
class MyQueue:
  def __init__(self, capacity):
    self.data = []
    self.capacity = capacity

  def enqueue(self,value):
      self.data.append(value)

  def dequeue(self):
    return self.data.pop(0)

  def is_empty(self):
    return len(self.data) == 0

  def is_full(self):
    return len(self.data) == self.capacity

  def front(self):
    return self.data[0]

queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
queue1 . enqueue (2)
print ( queue1 . is_full () )
print ( queue1 . front () )
print ( queue1 . dequeue () )
print ( queue1 . front () )
print ( queue1 . dequeue () )
print ( queue1 . is_empty () )


False
1
1
2
2
True


In [ ]:
#Trac nghiem 1/c
import torch
import torch.nn as nn

data = torch.Tensor ([1 , 2 , 3])
softmax_function = nn.Softmax ( dim =0)
output = softmax_function ( data )
assert round ( output [0]. item () , 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [ ]:
#Trac nghiem 2/b
import torch
import torch.nn as nn

class MySoftmax (nn.Module ) :
  def __init__ ( self ) :
    super ().__init__ ()

  def forward ( self , x ) :
    exp_x = torch.exp ( x )
    sum_exp_x = torch.sum(exp_x)
    return exp_x / sum_exp_x

data = torch . Tensor ([5 , 2 , 4])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [ -1]. item () , 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [ ]:
#Trac nghiem 3/c
import torch
import torch.nn as nn

class MySoftmax (nn.Module ) :
  def __init__ ( self ) :
    super ().__init__ ()

  def forward ( self , x ) :
    exp_x = torch.exp ( x )
    sum_exp_x = torch.sum(exp_x)
    return exp_x / sum_exp_x

data = torch . Tensor ([1 , 2 , 300000000])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [0]. item () , 2) == 0.0
output


tensor([0., 0., nan])

In [ ]:
#Trac nghiem 4/b

import torch
import torch.nn as nn

class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward ( self , x ) :
      x_max = torch .max(x , dim =0 , keepdims = True )
      x_exp = torch . exp ( x - x_max . values )
      partition = x_exp .sum (0 , keepdims = True )
      return x_exp / partition

data = torch . Tensor ([1 , 2 , 3])
softmax_stable = SoftmaxStable ()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

In [6]:
#Trac nghiem 5/a
from abc import ABC , abstractmethod
class Person ( ABC ) :
  def __init__ ( self , name :str , yob :int ) :
    self . _name = name
    self . _yob = yob

  def get_yob ( self ) :
    return self . _yob

  @abstractmethod
  def describe ( self ) :
    pass

class Student ( Person ) :
  def __init__ ( self , name :str , yob :int , grade :str) :
    super().__init__(name, yob)
    self.grade = grade

  def describe ( self ) :
    print ( f'Student - Name: {self._name} - YoB: {self._yob} - Grade: {self.grade}')

student1 = Student ( name =" studentZ2023 ", yob =2011 , grade ="6")
assert student1 . _yob == 2011
student1 . describe ()

Student - Name:  studentZ2023  - YoB: 2011 - Grade: 6


In [5]:
#Trac nghiem 6/b
from abc import ABC , abstractmethod
class Person ( ABC ) :
  def __init__ ( self , name :str , yob :int ) :
    self . _name = name
    self . _yob = yob

  def get_yob ( self ) :
    return self . _yob

  @abstractmethod
  def describe ( self ) :
    pass

class Teacher ( Person ) :
  def __init__ ( self , name :str , yob :int , subject : str) :
    super().__init__(name, yob)
    self.subject = subject

  def describe ( self ) :
    print ( f'Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self.subject}')

teacher1 = Teacher ( name =" teacherZ2023 ", yob =1991 , subject =" History ")
assert teacher1 . _yob == 1991
teacher1 . describe ()



Teacher - Name:  teacherZ2023  - YoB: 1991 - Subject:  History 


In [3]:
#Trac nghiem 7/a
from abc import ABC , abstractmethod

class Person ( ABC ) :
  def __init__ ( self , name :str , yob :int ) :
    self . _name = name
    self . _yob = yob

  def get_yob ( self ) :
    return self . _yob

  @abstractmethod
  def describe ( self ) :
    pass

class Doctor ( Person ) :
  def __init__ ( self , name :str , yob :int , specialist :str) :
    super().__init__(name, yob)
    self.specialist = specialist

  def describe ( self ) :
    print ( f'Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self.specialist}')

doctor1 = Doctor ( name =" doctorZ2023 ", yob =1981 , specialist =" Endocrinologists ")
assert doctor1 . _yob == 1981
doctor1 . describe ()



Doctor - Name:  doctorZ2023  - YoB: 1981 - Specialist:  Endocrinologists 


In [15]:
#Trac nghiem 8/c
class Ward :
  def __init__ ( self , name : str) :
    self . __name = name
    self . __listPeople = list ()

  def add_person ( self , person : Person ) :
    self . __listPeople . append ( person )

  def describe ( self ) :
    print ( f" Ward Name : { self . __name }")
    for p in self . __listPeople :
      p . describe ()

  def count_doctor ( self ) :
    count = sum(isinstance(person, Doctor) for person in self.__listPeople)
    return count


doctor2 = Doctor ( name =" doctorB ", yob =1975 , specialist =" Cardiologists ")
ward1 = Ward ( name =" Ward1 ")
ward1 . add_person ( student1 )
ward1 . add_person ( teacher1 )
ward1 . add_person ( teacher2 )
ward1 . add_person ( doctor1 )
ward1 . add_person ( doctor2 )
ward1 . count_doctor ()

2

In [16]:
#Trac nghiem 9/a
class MyStack :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __stack = []

  def is_full ( self ) :
    return len( self . __stack ) == self . __capacity

  def push ( self , value ) :
    self.__stack.append (value)

stack1 = MyStack ( capacity =5)
stack1 . push (1)
assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . is_full () )



False


In [22]:
#Trac nghiem 10/b
class MyStack :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __stack = []

  def is_full ( self ) :
    return len( self . __stack ) == self . __capacity

  def push ( self , value ) :
    self.__stack.append (value)

  def top ( self ) :
    return self.__stack[-1]

  def describe(self):
    print(self.__stack)

stack1 = MyStack ( capacity =5)
stack1 . push (1)
assert stack1 . is_full () == False
stack1 . push (2)
print ( stack1 . top () )

2


In [23]:
#Trac nghiem 11/a
class MyQueue :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __queue = []

  def is_full ( self ) :
    return len( self . __queue ) == self . __capacity

  def enqueue ( self , value ) :
    self.__queue.append (value)

queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
assert queue1 . is_full () == False
queue1 . enqueue (2)
print ( queue1 . is_full () )




False


In [24]:
#Trac nghiem 11/d
class MyQueue :
  def __init__ ( self , capacity ) :
    self . __capacity = capacity
    self . __queue = []

  def isEmpty ( self ) :
    return len( self . __queue ) == 0

  def is_full ( self ) :
    return len( self . __queue ) == self . __capacity

  def dequeue ( self ) :
    return self.__queue.pop(0)

  def enqueue ( self , value ) :
    self.__queue.append (value)

  def front ( self ) :
    return self.__queue[0]


queue1 = MyQueue ( capacity =5)
queue1 . enqueue (1)
assert queue1 . is_full () == False
queue1 . enqueue (2)
print ( queue1 . front () )


1
