<a href="https://colab.research.google.com/github/ngohuy1811/AIO-Module_1/blob/main/numpy_programming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Cau 1: a
import numpy as np

arr1 = np . arange (0 , 10 , 1)
print (arr1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Cau 2: b
arr2 = np . full ((3 ,3) , fill_value = True , dtype = bool )
print (arr2)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#Cau 3: a
arr = np . arange (0 ,10)
print ( arr [ arr %2 == 1])

[1 3 5 7 9]


In [ ]:
#Cau 4: b
arr = np . arange (0 ,10)
arr [ arr %2 ==1] = -1
print ( arr )

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
#Cau 5: b
arr = np . arange (10)
arr_2d = arr . reshape (2 , -1)
print ( arr_2d )

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#Cau 6: a
arr1 = np.arange (10) . reshape (2 , -1)
arr2 = np.repeat (1 ,10) . reshape (2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =0)
print (" Result : \n", c )

 Result : 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#Cau 7: c
arr1 = np.arange (10) . reshape (2 , -1)
arr2 = np.repeat (1 ,10) . reshape (2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =1)
print (" Result : \n", c )


 Result : 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [ ]:
#Cau 8:a
arr = np . array ([1 ,2 ,3])
print ( np . repeat ( arr ,3) )
print ( np . tile ( arr ,3) )



[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [ ]:
#Cau 9:c
a = np . array ([2 ,6 ,1 ,9 ,10 ,3 ,27])
index = np . where ((a >=5) &( a <=10) )
print (" result ", a [ index ])

 result  [ 6  9 10]


In [ ]:
#Cau 10: d
def maxx(x, y):
  if x >= y:
    return x
  else:
    return y

x = np.array([5, 7, 9, 8, 6, 4, 5])
y = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(x,y))

[6. 7. 9. 8. 9. 7. 5.]


In [ ]:
#Cau 11: a
a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

print ("Result", np . where (a <b , b , a ) )

Result [6 7 9 8 9 7 5]


In [ ]:
#Cau 12: a
# Download image

! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
import matplotlib.image as mpimg

img = mpimg.imread('/content/dog.jpeg')
def lightness_method(rgb_image):
  grayscale_image = (np.max(rgb_image, axis=2) + np.min(rgb_image, axis=2)) / 2
  return grayscale_image

gray_img_01 = lightness_method(img)
gray_img_01 [0,0]





Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 42.3MB/s]


102.5

In [ ]:
#Cau 13: a
# Download image
! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')

import numpy as np
def average_method(rgb_image):
  grayscale_image = np.mean(rgb_image, axis=2)
  return grayscale_image

gray_img_02 = average_method(img)
gray_img_02 [0 , 0]


Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 63.8MB/s]


107.66666666666667

In [ ]:
#Cau 14: c
import matplotlib.image as mpimg

img = mpimg.imread('/content/dog.jpeg')
import numpy as np

def luminosity_method(rgb_image):
    grayscale_image = 0.21 * rgb_image[:,:,0] + 0.72 * rgb_image[:,:,1] + 0.07 * rgb_image[:,:,2]
    return grayscale_image

gray_img_03 = luminosity_method(img)
gray_img_03[0 , 0]

126.22999999999999

In [ ]:
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv ('/content/advertising.csv')

data = df.to_numpy()

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 17.7MB/s]


In [ ]:
#Cau 15: c
max_index = df['Sales'].idxmax()
max_value = df['Sales'].max()
print(max_value, max_index)

27.0 175


In [ ]:
#Cau 16: b
mean_tv = df['TV'].mean()
print(mean_tv)

147.0425


In [ ]:
#Cau 17: a
count_sales_ge_20 = df[df['Sales'] >= 20].shape[0]
print(count_sales_ge_20)

40


In [ ]:
#Cau 18: b
filtered_df = df[df['Sales'] >= 15]
mean_radio = filtered_df['Radio'].mean()
print(mean_radio)

26.22293577981651


In [ ]:
#Cau 19: c
mean_newspaper = df['Newspaper'].mean()
filtered_df = df[df['Newspaper'] > mean_newspaper]
sum_sales = filtered_df['Sales'].sum()
print(sum_sales)

1405.1


In [ ]:
#Cau 20: c
A = df['Sales'].mean()
scores = df['Sales'].apply(lambda x: 'Good' if x > A else 'Bad' if x < A else 'Average').to_list()
print(scores[7:10])

['Bad', 'Bad', 'Good']


In [ ]:
#Cau 21: c
mean_sales = df['Sales'].mean()
A = df['Sales'].iloc[(df['Sales'] - mean_sales).abs().argsort()[:1]].values[0]
scores = df['Sales'].apply(lambda x: 'Good' if x > A else 'Bad' if x < A else 'Average').to_list()
print(scores[7:10])

['Bad', 'Bad', 'Good']
